cache:
  directories:
  - $HOME/.m2/repository

jdk:
- openjdk8
- openjdk11

install: ./mvnw --show-version --batch-mode -DskipTests=true -Dgpg.skip=true --activate-profiles sonatype-oss-release install

language: java

script: ./mvnw --batch-mode verify
